package io.baleia.trino.catalogstore;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.type.CollectionType;
import io.trino.spi.catalog.CatalogName;
import io.trino.spi.connector.ConnectorName;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Golden test for {@link BaleiaCatalogStore#computeCatalogVersion}.
 *
 * <p>The algorithm replicates {@code FileCatalogStore.computeCatalogVersion} from Trino 482:
 * <ul>
 *   <li>SHA-256</li>
 *   <li>{@code "catalog-hash"} written as UTF-16LE <b>without</b> length prefix</li>
 *   <li>for each string (catalog name, connector name, every key and value):</li>
 *   <li>{@code putInt(length)} in little-endian (4 bytes), followed by
 *       {@code putUnencodedChars} which is UTF-16LE (2 bytes per char)</li>
 *   <li>{@code putInt(properties.size())}</li>
 *   <li>iteration in ascending key alphanumeric order (ImmutableSortedMap)</li>
 * </ul>
 *
 * <p>The shared vectors live in {@code src/test/resources/catalog_version_vectors.json}. The
 * Go side of this contract consumes the same JSON (the file ships in the repo under
 * {@code catalogs/testdata/}) and implements the algorithm in
 * {@code backend/internal/catalogs.Version}. Both sides MUST produce every hash in the file.
 */
class ComputeCatalogVersionTest
{
    /**
     * Known SHA-256 hash for:
     *   name        = "tpch_teste"
     *   connector   = "tpch"
     *   properties  = { "tpch.splits-per-node": "4" }
     *
     * <p>Generated by the Guava implementation of
     * {@link BaleiaCatalogStore#computeCatalogVersion} against Trino 482.
     * Serves as a fixed golden value: if it ever breaks, either Guava changed endianness
     * (rare) or the algorithm was changed (bad). The Go implementation must produce
     * exactly this same value. This constant duplicates the first row of
     * {@code catalog_version_vectors.json} so a regression is caught by name.
     */
    static final String GOLDEN = "c4927418429a39beae1c13b2c9f02adba0c554e8f7d450d170d323b1997c3b82";

    @Test
    void computesVersionFromCatalogNameAndConnectorNameAndProperties()
    {
        CatalogName name = new CatalogName("tpch_teste");
        ConnectorName connector = new ConnectorName("tpch");
        Map<String, String> props = Map.of("tpch.splits-per-node", "4");

        var version = BaleiaCatalogStore.computeCatalogVersion(name, connector, props);

        // Sanity check: it's a SHA-256 hex string (64 lowercase chars).
        assertEquals(64, version.toString().length());
        assertEquals(version.toString(), version.toString().toLowerCase());
        assertEquals(GOLDEN, version.toString(),
                "hash diverged from golden value — regenerate and update this test");
    }

    /**
     * Iterate the shared vectors JSON. For each vector:
     * <ul>
     *   <li>compute the hash with the Guava-backed {@link BaleiaCatalogStore#computeCatalogVersion};</li>
     *   <li>compute the hash with a reference MessageDigest implementation that mirrors the
     *       Guava byte encodings (little-endian putInt, UTF-16LE putUnencodedChars) — this is
     *       the contract the Go impl has to reproduce;</li>
     *   <li>assert both are equal AND both equal the recorded {@code expected_hash}.</li>
     * </ul>
     *
     * <p>The vector file lives at {@code src/test/resources/catalog_version_vectors.json}.
     * To add a vector or reset a hash, edit it; on the first run with "REPLACE" as the
     * expected_hash this test fails and the failure message prints the actual value.
     */
    @Test
    void catalogVectorsMatchExpectedHashes()
            throws IOException
    {
        List<Vector> vectors;
        try (InputStream in = ComputeCatalogVersionTest.class.getResourceAsStream(
                "/catalog_version_vectors.json")) {
            if (in == null) {
                throw new IllegalStateException(
                        "catalog_version_vectors.json not found on the test classpath");
            }
            ObjectMapper mapper = new ObjectMapper();
            CollectionType listType = mapper.getTypeFactory()
                    .constructCollectionType(List.class, Vector.class);
            vectors = mapper.readValue(in, listType);
        }

        // No vector file means no contract. If you delete the file, this test must fail
        // loudly, not silently pass.
        if (vectors.isEmpty()) {
            throw new IllegalStateException("catalog_version_vectors.json contains no vectors");
        }

        StringBuilder failures = new StringBuilder();
        for (Vector v : vectors) {
            CatalogName name = new CatalogName(v.name());
            ConnectorName connector = new ConnectorName(v.connector());
            Map<String, String> props = new LinkedHashMap<>(v.properties());
            var guava = BaleiaCatalogStore.computeCatalogVersion(name, connector, props);
            var ref = referenceCatalogVersion(v.name(), v.connector(), props);

            if (!ref.equals(guava.toString())) {
                failures.append("- ").append(v.name())
                        .append(": Guava (").append(guava)
                        .append(") != MessageDigest (").append(ref)
                        .append(") — Java-side inconsistency\n");
            }
            if (!v.expectedHash().equals(guava.toString())) {
                failures.append("- ").append(v.name())
                        .append(": recorded expected_hash (").append(v.expectedHash())
                        .append(") != actual (").append(guava).append(")\n");
            }
        }
        if (!failures.isEmpty()) {
            // JUnit gets the diff plus the resolution hints.
            String help = """

                    --- HINT ---
                    To refresh hashes in catalog_version_vectors.json, copy the `actual`
                    values above into the matching `expected_hash` field. Do NOT refresh
                    vectors whose expected_hash already matches — those are the contract.
                    """ + failures;
            throw new AssertionError("catalog vector hash mismatches:\n" + help);
        }
    }

    @Test
    void stableForSameInputOrderIndependent()
    {
        CatalogName name = new CatalogName("vendas");
        ConnectorName connector = new ConnectorName("iceberg");
        Map<String, String> a = new LinkedHashMap<>();
        a.put("x", "1");
        a.put("y", "2");
        Map<String, String> b = new LinkedHashMap<>();
        b.put("y", "2");
        b.put("x", "1");

        var v1 = BaleiaCatalogStore.computeCatalogVersion(name, connector, a);
        var v2 = BaleiaCatalogStore.computeCatalogVersion(name, connector, b);

        assertEquals(v1, v2, "hash must be independent of insertion order");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Reference implementation — this is what the Go code must reproduce.
    // ─────────────────────────────────────────────────────────────────────────
    static String referenceCatalogVersion(String catalogName, String connectorName, Map<String, String> properties)
    {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            putUnencodedChars(md, "catalog-hash");
            hashLengthPrefixedString(md, catalogName);
            hashLengthPrefixedString(md, connectorName);
            putIntLittleEndian(md, properties.size());
            // TreeMap to replicate ImmutableSortedMap.copyOf (natural key ordering).
            new TreeMap<>(properties).forEach((k, v) -> {
                hashLengthPrefixedString(md, k);
                hashLengthPrefixedString(md, v);
            });
            byte[] digest = md.digest();
            return toHex(digest);
        }
        catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private static void hashLengthPrefixedString(MessageDigest md, String s)
    {
        putIntLittleEndian(md, s.length());
        putUnencodedChars(md, s);
    }

    private static void putUnencodedChars(MessageDigest md, String s)
    {
        // UTF-16LE: 2 bytes per char, exactly like Guava Hasher.putUnencodedChars
        md.update(s.getBytes(StandardCharsets.UTF_16LE));
    }

    private static void putIntLittleEndian(MessageDigest md, int v)
    {
        // Guava Hasher.putInt: little-endian, 4 bytes
        md.update((byte) (v & 0xff));
        md.update((byte) ((v >> 8) & 0xff));
        md.update((byte) ((v >> 16) & 0xff));
        md.update((byte) ((v >> 24) & 0xff));
    }

    private static String toHex(byte[] bytes)
    {
        StringBuilder sb = new StringBuilder(bytes.length * 2);
        for (byte b : bytes) {
            sb.append(Character.forDigit((b >> 4) & 0xf, 16));
            sb.append(Character.forDigit(b & 0xf, 16));
        }
        return sb.toString();
    }

    /** Wire shape of an entry in {@code catalog_version_vectors.json}. */
    public record Vector(
            String name,
            String connector,
            Map<String, String> properties,
            @com.fasterxml.jackson.annotation.JsonProperty("expected_hash") String expectedHash,
            String note)
    {
        public Vector
        {
            if (name == null || name.isEmpty()) {
                throw new IllegalArgumentException("vector missing 'name'");
            }
            if (connector == null || connector.isEmpty()) {
                throw new IllegalArgumentException("vector '" + name + "' missing 'connector'");
            }
            if (properties == null) {
                properties = Map.of();
            }
            if (expectedHash == null) {
                expectedHash = "REPLACE";
            }
        }
    }
}